config/routes.rb
Rails.application.routes.draw do
  get 'subscribers/create'
  
  get 'questions/show'
  get 'topics/index'
  get 'topics/show'
  get 'subjects/index'
  get 'subjects/show'
  
  resources :subjects do
    resources :topics, only: [:index, :new, :create]
  end
  
  resources :topics, except: [:index] do
    resources :sub_topics, only: [:index, :new, :create]
    resources :questions, only: [:new, :create]
  end
  
  resources :sub_topics, except: [:index, :new, :create]
  
  resources :questions, except: [:index, :new, :create]
  
  resources :badges
  
  resources :institutions do
    member do
      get :analytics_dashboard
      get :executive_summary
      get :engagement_analytics
      get :quiz_performance
      get :subject_breakdown
      get :student_distribution
      get :temporal_analysis
      get :comparative_analysis
      get :export_report
    end
  end
  
  resources :worlds do
    resources :levels do
      member do
        get :start_quiz
        get :level_preview
      end
    end
  end
  
  # Quiz routes
  get 'quiz/start', to: 'quiz#start', as: 'quiz_start'
  get 'quiz/question', to: 'quiz#question', as: 'quiz_question'
  get 'quiz/previous', to: 'quiz#previous_question', as: 'quiz_previous_question'
  post 'quiz/submit', to: 'quiz#submit', as: 'quiz_submit'
  get 'quiz/results', to: 'quiz#results', as: 'quiz_results'
  get 'quiz/history', to: 'quiz#history', as: 'quiz_history'
  get 'quiz/sessions', to: 'quiz#sessions', as: 'quiz_sessions'
  get 'quiz/quiz_select', to: 'quiz#quiz_select', as: 'quiz_select'
  get 'quiz/sessions/:id', to: 'quiz#show_session', as: 'quiz_session'
  get 'quiz/resume/:id', to: 'quiz#resume', as: 'resume_quiz'
  
  post 'quiz/sessions/:quiz_session_id/feedback', to: 'feedbacks#create', as: 'quiz_session_feedbacks'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  get 'users/user_new', to: 'users#user_new', as: 'user_new_user'
  post 'users/user_create', to: 'users#user_create', as: 'user_create_user'
  get 'users/:id/user_edit', to: 'users#user_edit', as: 'user_edit_user'
  patch 'users/:id/user_update', to: 'users#user_update', as: 'user_update_user'
  post 'reset_progress', to: 'users#reset_progress'
  get 'social', to: 'users#social', as: 'social'
  get '/profile/:nickname', to: 'users#profile', as: :profile
  get 'find_users', to: 'users#find_users', as: :find_users
  get 'mark_new_followers_seen', to: 'users#mark_new_followers_seen'
  
  resources :users do
    
    # Following routes
    post 'follows', to: 'user_follows#create'
    delete 'follows', to: 'user_follows#destroy'
     
    # Following-related pages
    get 'following', to: 'user_follows#following'
    get 'followers', to: 'user_follows#followers'
    get 'mutual', to: 'user_follows#mutual'
  end
  
  resources :study_groups do
    member do
      post :join
      get :leave
      get :invite_user
    end
    
    resources :study_group_memberships, only: [:destroy], path: 'members' do
      member do
        get :promote
        get :demote
      end
    end
    
    collection do
      get :leaderboards
    end
  end
  
  resources :study_group_invitations, only: [:index, :show] do
    member do
      get :accept
      get :decline
    end
  end
  
  authenticated :user, -> (user) { user.teacher? || user.admin? } do
    root to: "pages#teacher_dashboard", as: :teacher_root
  end
    
  authenticated :user, -> (user) { user.institution_admin? } do
    root to: "institutions#redirect_to_institution", as: :institution_root
  end
  
  authenticated :user, -> (user) { !user.teacher? && !user.admin? } do
    root to: "pages#home", as: :authenticated_root
  end
  
  # Unauthenticated user routes
  unauthenticated do
    root "pages#landing_page"
  end
  
  resources :subscribers, only: [:create]
  
  get 'pages/home', to: 'pages#home'
  get 'teacher_dashboard', to: 'pages#teacher_dashboard'
  get 'reports', to: 'pages#reports', as: 'reports'
  get 'configuration', to: 'pages#configuration', as: 'configuration'
  
  get 'pages/about'
  get 'pages/our_team'
  get 'pages/our_blog'
  get 'pages/csec_quizzes'
  get 'pages/contact_us'
  get 'pages/faqs'
  
  get 'leaderboard', to: 'leaderboard#index', as: 'leaderboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  
  def create
    super do |resource|
      # Only send email if the user was successfully created
      if resource.persisted?
        UserMailer.welcome_email(resource).deliver_later
      end
    end
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :country,
    :quiz_attempts, :max_quiz_attempts, :nickname])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :country,
    :quiz_attempts, :max_quiz_attempts, :nickname])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin, except: [:show, :user_edit, :user_update, :reset_progress, :social, :profile,
  :find_users, :mark_new_followers_seen]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    # Generate a random password if none provided
    @user.password = SecureRandom.hex(8) if @user.password.blank?
    
    if @user.save
      redirect_to users_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def user_new
    @user = User.new
  end
  
  def user_create
    @user = User.new(user_params)
    
    # Skip password validation and generate password if none provided
    generated_password = nil
    if @user.password.blank?
      @user.skip_password_validation = true
      generated_password = SecureRandom.hex(8)
      @user.password = generated_password
      @user.password_confirmation = generated_password
    end
    
    if @user.save
      
      if @user.teacher? && params[:user][:assigned_subject_ids].present?
        subject_ids = params[:user][:assigned_subject_ids].reject(&:blank?)
        subject_ids.each do |subject_id|
          subject = Subject.find_by(id: subject_id)
          @user.assign_to_subject!(subject) if subject
        end
      end
      
      if @user.institution_admin?
        UserMailer.institution_welcome_email(@user).deliver_later
      elsif @user.teacher?
        UserMailer.teacher_welcome_email(@user, generated_password).deliver_later
      elsif @user.student?
        UserMailer.welcome_email(@user).deliver_later
      end
      redirect_to users_path, notice: "User was successfully created."
    else
      render :user_new, status: :unprocessable_entity
    end
  end
  
  def user_edit
    @user = User.find(params[:id])
    @include_password = true
  end
  
  def user_update
    @user = User.find(params[:id])
    
    if @user.update_with_password(user_params)
      
      redirect_to user_path(@user), notice: "User was successfully updated."
    else
      render :user_edit, status: :unprocessable_entity
    end
  end
  
  def show
    @user = User.find(params[:id])
    
    # Security check: only admins can view any user profile
    # Regular users can only view their own profile
    #unless current_user.admin? || current_user == @user
      #redirect_to root_path, alert: "You are not authorized to view this profile."
      #return
    #end
  end
  
  def profile
    @user = User.find_by!(nickname: params[:nickname])
  end
  
  def reset_progress
    if current_user.reset_progress!
      redirect_to user_path(current_user), notice: "Your progress has been reset successfully!"
    else
      redirect_to user_path(current_user), alert: "There was an error resetting your progress."
    end
  end
  
  def social
    @user = current_user
    @recent_followers = @user.followers.order(created_at: :desc).limit(5)
    #@suggested_follows = @user.suggested_follows
    @mutual_follows = @user.mutual_follows.limit(5)
    @following_activity = @user.following_activity
    
    @new_followers = @user.new_follows
    #@new_followers.update_all(new_follow: false) if @new_followers.any?
  end
  
  def mark_new_followers_seen
    current_user.passive_follows.where(new_follow: true).update_all(new_follow: false)
    redirect_back(fallback_location: social_path)
  end
  
  #def mark_new_invitations_seen
    #current_user.received_study_group_invitations.where(new_invitation: true).update_all(new_invitation: false)
    #redirect_back(fallback_location: social_path)
  #end
  
  def find_users
    @search_query = params[:search]
    @users = User.none  # Start with empty relation
    
    if @search_query.present?
      # Search by nickname (case-insensitive)
      search_term = "%#{@search_query.downcase}%"
      @users = User.where("LOWER(nickname) LIKE ?", search_term)
                   .where.not(id: current_user.id)  # Exclude current user
                   .includes(:institution, :user_badges, :badges)
                   .order(:nickname)
      
      # Optionally limit results to prevent performance issues
      @users = @users.limit(50)
    end
    
    # Track search analytics (optional)
    if @search_query.present? && @users.any?
      Rails.logger.info "User search: '#{@search_query}' returned #{@users.count} results"
    end
  end
  
  private
  
  def require_admin
    unless current_user.admin?
      redirect_to authenticated_root_path, alert: "You are not authorized to access this page."
    end
  end
  
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :role, :password, 
    :password_confirmation, :country, :quiz_attempts, :max_quiz_attempts, :nickname, :institution_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def can_remove_member?(current_user_membership, target_membership)
    return false unless current_user_membership
    
    # Leaders can remove admins and members (but not other leaders or themselves)
    if current_user_membership.leader?
      return false if target_membership.leader? # Can't remove other leaders
      return true if target_membership.admin? || target_membership.member?
    end
    
    # Admins can only remove regular members (not other admins or leaders)
    if current_user_membership.admin?
      return true if target_membership.member?
      return false # Can't remove admins or leaders
    end
    
    false # Members can't remove anyone
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user, url: url, method: method do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <%= f.input :first_name, required: true %>
      </div>
      <div class="col-md-6">
        <%= f.input :last_name, required: true %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <%= f.input :nickname, required: true, label: "Display Name" %>
      </div>
    </div>
    
    <%= f.input :email, required: true %>
    
    <div class="row">
      <div class="col-md-6">
        <%= f.input :password, required: false, hint: "Leave blank to keep current password" %>
      </div>
      <div class="col-md-6">
        <%= f.input :password_confirmation, required: false %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= f.input :country %>
      </div>
    </div>
    
    <% if current_user.admin? %>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :role, 
                      collection: User::roles.keys, label_method: lambda { |role| role.titleize }, 
                      required: true %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-6">
          <%= f.input :institution_id, collection: Institution.all, placeholder: 'Type to find business category',
          input_html: {data: {controller: 'slim-select'}} %>
        </div>
      </div>
      
      <%= f.association :assigned_subjects,
                  collection: Subject.all, 
                  label_method: :name,
                  value_method: :id,
                  input_html: { 
                    multiple: true,
                    data: { controller: 'slim-select' }
                  },
                  hint: "Select subjects for teachers (only applies to teacher role)" %>
      
      <div class="row">
        <div class="col-md-6">
          <%= f.input :quiz_attempts %>
        </div> 
        
        <div class="col-md-6">
          <%= f.input :max_quiz_attempts %>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="form-actions mt-4">
    <%= f.button :submit, submit_text, class: 'btn-primary' %>
    <%= link_to "Cancel", cancel_path, class: "btn btn-outline-primary ms-2" %>
  </div>
<% end %>

app/views/users/admin_edit.html.erb
<div class="container mt-4">
  <% if current_user.admin? %>
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-white">
            <li class="breadcrumb-item"><%= link_to "Users", users_path %></li>
            <li class="breadcrumb-item"><%= link_to "#{@user.first_name} #{@user.last_name}", user_path(@user) %></li>
            <li class="breadcrumb-item active" aria-current="page">Edit</li>
          </ol>
        </nav>
      </div>
    </div>
  <% end %>
  
  <h3>Edit <%= @user.name %></h3>
  <%= render 'form', 
             url: admin_update_user_path(@user), 
             method: :patch,
             include_password: false,
             submit_text: "Update User",
             cancel_path: user_path(@user) %>

</div>

app/views/users/admin_new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-white">
          <li class="breadcrumb-item"><%= link_to "Users", users_path %></li>
          <li class="breadcrumb-item active" aria-current="page">New User</li>
        </ol>
      </nav>
    </div>
  </div>


  <h3>Create New User</h3>
  <%= render 'form', 
             url: admin_create_user_path, 
             method: :post,
             include_password: true,
             submit_text: "Create User",
             cancel_path: users_path %>

</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="card border-0">
    <div class="card-header d-flex justify-content-between align-items-center bg-white border-0">
      <h2 class="mb-0">All Users</h2>
      <div>
        <%= link_to "New User", user_new_user_path, class: "btn btn-primary btn-sm" %>
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Joined</th>
              <th>Quiz Attempts</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= "#{user.first_name} #{user.last_name}".strip %>
                  <% if user == current_user %>
                    <span class="badge bg-dark ms-1">You</span>
                  <% end %>
                </td>
                <td><%= user.email %></td>
                <td>
                    <%= user.role.humanize %>
                </td>
                <td><%= user.created_at.strftime('%b %d, %Y') %></td>
                <td><%= user.question_attempts.count %></td>
                <td>
                  <div class="btn-group btn-group-sm" role="group">
                    <%= link_to "View", user_path(user), class: "btn btn-outline-primary" %>
                    <%= link_to "Edit", user_edit_user_path(user), class: "btn btn-outline-primary" %>
                    <% unless user == current_user %>
                      <%= link_to "Delete", user_path(user), 
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this user? This action cannot be undone." }, 
                          class: "btn btn-outline-danger" %>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <% if @users.empty? %>
        <div class="alert alert-info">
          No users found.
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-4">
    <h3>User Statistics</h3>
    <div class="row">
      <div class="col-md-3">
        <div class="card bg-light">
          <div class="card-body text-center">
            <h3><%= @users.count %></h3>
            <p class="mb-0">Total Users</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-light">
          <div class="card-body text-center">
            <h3><%= @users.where(role: 'admin').count %></h3>
            <p class="mb-0">Administrators</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-light">
          <div class="card-body text-center">
            <h3><%= @users.where(role: 'teacher').count %></h3>
            <p class="mb-0">Teachers</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-light">
          <div class="card-body text-center">
            <h3><%= @users.where(role: 'student').count %></h3>
            <p class="mb-0">Students</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/social.html.erb
<div class="container px-4" id="social-dashboard">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="display-6 fw-bold">Social Dashboard</h2>
  </div>
  
  <% if @user.pending_study_group_invitations.any? %>
    <div class="mb-4 alert alert-info alert-dismissible fade show" role="alert" id="pending-invitations-alert">
      <i class="bi bi-envelope-plus-fill me-2"></i>
      <strong>Study Group Invitations!</strong> 
      You have <%= pluralize(@user.pending_study_group_invitations.count, 'pending invitation') %>:
      
      <div class="mt-2">
        <% @user.pending_study_group_invitations.each do |invitation| %>
          <div class="d-flex align-items-center justify-content-between rounded p-2 mb-2">
            <div>
              <span class="fw-medium">Study group <b><%= invitation.study_group.name %></b></span>
              <small class="text-white d-block">
                Invited by <%= invitation.inviter.name %> 
                <%= time_ago_in_words(invitation.created_at) %> ago
              </small>
            </div>
            <div class="btn-group btn-group-sm">
              <%= link_to "Accept", accept_study_group_invitation_path(invitation),
                  class: "btn btn-success btn-sm",
                  data: { 
                    turbo_method: :get,
                    turbo_confirm: "Join #{invitation.study_group.name}?" 
                  } %>
              <%= link_to "Decline", decline_study_group_invitation_path(invitation),
                  class: "btn btn-danger btn-sm",
                  data: { 
                    turbo_method: :get,
                    turbo_confirm: "Decline invitation to #{invitation.study_group.name}?" 
                  } %>
            </div>
          </div>
        <% end %>
      </div>
      
      <button type="button" class="btn-close" data-bs-dismiss="alert" id="close-invitations"></button>
    </div>
  <% end %>
  
  <% if @new_followers.any? %>
    <div class="mb-4 alert alert-success alert-dismissible fade show" role="alert" id="new-followers-alert">
      <i class="bi bi-person-plus-fill me-2"></i>
      <strong>New Followers!</strong> 
      <%= pluralize(@new_followers.count, 'person') %> started following you:
      
      <div class="mt-2">
        <% @new_followers.each do |follow| %>
          <span class="badge bg-primary me-1">
            <%= link_to follow.follower.name, profile_path(follow.follower.nickname), 
                class: "text-white text-decoration-none" %>
          </span>
        <% end %>
      </div>
      
      <button type="button" class="btn-close" data-bs-dismiss="alert" id="close-new-followers"></button>
    </div>
    
    <script>
      document.getElementById('close-new-followers').addEventListener('click', function() {
        // Mark as seen when closing
        fetch('<%= mark_new_followers_seen_path %>', {
          method: 'GET',
          headers: {
            'X-CSRF-Token': document.querySelector('[name="csrf-token"]').content,
            'Content-Type': 'application/json'
          }
        });
      });
    </script>
  <% end %>
  
  <!-- Followers Card -->
  <div class="card hover-card border-0 shadow-sm mb-5">
    <div class="card-header bg-white d-flex justify-content-between align-items-center">
      <h4 class="mb-0 text-body-emphasis">
        <i class="bi bi-person-hearts me-2"></i>
        Followers
      </h4>
      <div class="btn-group" role="group">
        <%= link_to user_following_path(@user), class: "btn btn-outline-primary btn-sm" do %>
          View Following
        <% end %>
        <%= link_to user_followers_path(@user), class: "btn btn-outline-primary btn-sm" do %>
          View Followers
        <% end %>
        <%= link_to find_users_path, class: "btn btn-sm btn-primary" do %>
          <i class="bi bi-search me-1"></i>Find Users
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col-12 col-md-9 mt-3 mt-md-0">
          <div class="d-flex flex-wrap gap-2">
            <!-- Following & Followers Avatars Section -->
            <div class="">
              <% if @user.followers.any? %>
                <!-- Followers Avatars -->
                <% if @user.followers.any? %>
                  <div class="mb-3">
                    <div class="d-flex flex-wrap gap-3">
                      <% @user.followers.limit(6).each_with_index do |follower, index| %>
                        <div class="text-center position-relative">
                          <%= link_to profile_path(follower.nickname), class: "text-decoration-none" do %>
                            <div class="avatar-circle bg-success text-white d-flex align-items-center justify-content-center mb-2" 
                                 style="width: 60px; height: 60px; border-radius: 50%; font-size: 0.75rem;">
                              <%= follower.initials %>
                            </div>
                            <small class="text-muted d-block" style="font-size: 0.7rem;">
                              <%= follower.nickname %>
                            </small>
                          <% end %>
                          
                          <!-- Show mutual follow indicator -->
                          <% if current_user&.following?(follower) %>
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning" 
                                  style="font-size: 0.5rem; margin-top: 3px; margin-left: -3px;" 
                                  title="Mutual follow">
                              <i class="bi bi-arrow-left-right"></i>
                            </span>
                          <% end %>
                        </div>
                      <% end %>
                      
                      <% if @user.followers_count > 6 %>
                        <%= link_to user_followers_path(@user), class: "text-decoration-none" do %>
                          <div class="text-center">
                            <div class="avatar-circle bg-light text-muted d-flex align-items-center justify-content-center mb-2" 
                                 style="width: 60px; height: 60px; border-radius: 50%; border: 2px dashed #dee2e6; font-size: 0.65rem;">
                              +<%= @user.followers_count - 6 %>
                            </div>
                            <small class="text-muted d-block" style="font-size: 0.7rem;">more</small>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <!-- Empty State -->
                <div class="text-center">
                  <div class="mb-3">
                    <i class="bi bi-people text-muted" style="font-size: 3rem;"></i>
                  </div>
                  <h6 class="text-muted mb-2">No social connections yet</h6>
                  <p class="text-muted small mb-3">Start following other users to build your network!</p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-3 text-md-end mt-3 mt-md-0">
          <p class="text-muted mb-1">
            <strong><%= @user.followers_count %></strong> followers | <strong><%= @user.following_count %></strong> following
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Study Group Section -->
  <div class="card hover-card border-0 shadow-sm mb-5">
    <div class="card-header bg-white d-flex justify-content-between align-items-center">
      <h4 class="mb-0 text-body-emphasis">
        <i class="bi bi-people-fill text-primary me-2"></i>
        My Study Group
      </h4>
      <% if @user.is_study_group_member? %>
        <%= link_to "Group Details", study_group_path(@user.current_study_group), class:"btn btn-outline-primary btn-sm" %>
      <% else %>
        <%= link_to new_study_group_path, class: "btn btn-sm btn-primary" do %>
          <i class="bi bi-plus me-1"></i>Create Study Group
        <% end %>
      <% end %>
      
    </div>
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col-12 col-md-3">
          <h5 class="text-primary mb-2"><%= @user.is_study_group_member? ? @user.current_study_group.name : "No study group yet" %></h5>
          <small class="text-muted"><%= @user.is_study_group_member? ? format_date(@user.current_study_group.created_at) : "You can join a study group or create your own!" %></small>
        </div>
        <div class="col-12 col-md-6 mt-3 mt-md-0">
          <div class="d-flex flex-wrap gap-2">
            <% if @user.is_study_group_member? %>
              <% @user.current_study_group.members.limit(5).each do |student| %>
                <%= link_to profile_path(student.nickname) do %>
                  <div class="text-center text-white">
                    <div class="avatar-circle mx-auto" style="background: linear-gradient(135deg, #22c55e 0%, #15803d 100%);">
                        <%= student.initials %>
                    </div>
                    <small class="d-block mt-2 text-black"><%= student.name %></small>
                  </div>
                <% end %>
              <% end %>
              <!-- More indicator -->
              <div class="text-center">
                <div class="avatar-circle bg-light text-muted d-flex align-items-center justify-content-center" 
                     style="width: 60px; height: 60px; border-radius: 50%; border: 2px dashed #dee2e6;">
                  <span style="font-size: 0.8rem;">+<%= @user.institution.users.where(role: :student).count - 5 %></span>
                </div>
              </div>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-12 col-md-3 text-md-end mt-3 mt-md-0">
          <p class="text-muted mb-1">
            <% if @user.is_study_group_member? %>
              <strong><%= @user.current_study_group.members.count %></strong> members
            <% end %>
          </p>
          <small class="text-muted"><%= @user.is_study_group_member? ? "#{@user.current_study_group.total_points} total points" : "" %></small>
        </div>
      </div>
    </div>
  </div>

  <!-- Institution Section -->
  <% if !current_user.institution.nil? %>
  <div class="card hover-card border-0 shadow-sm mb-5">
    <div class="card-header bg-white d-flex justify-content-between align-items-center">
      <h4 class="mb-0 text-body-emphasis">
        <i class="bi bi-building me-2"></i>
        My Institution
      </h4>
      <%= link_to "View Institution", institution_path(@user.institution), class:"btn btn-outline-primary btn-sm" %>
    </div>
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col-12 col-md-3">
          <div class="d-flex align-items-center mb-3">
            <%= image_tag @user.institution.institution_logo, 
              alt: @user.institution.name,
              class: "institution-logo-thumb  p-2 mx-2" if @user.institution.institution_logo.attached? %>
            <div>
                <h5 class="mb-2"><%= @user.institution.name %></h5>
            </div>
          </div>
          <small class="text-muted">Rank #3 on VerdGem Quiz</small>
        </div>
        <div class="col-12 col-md-6 mt-3 mt-md-0">
          <div class="d-flex flex-wrap gap-2">
            <% @user.institution.users.where(role: :student).limit(5).each do |student| %>
              <%= link_to user_path(student) do %>
                <div class="text-center text-white">
                  <div class="avatar-circle mx-auto" style="background: linear-gradient(135deg, #22c55e 0%, #15803d 100%);">
                      <%= student.initials %>
                  </div>
                  <small class="d-block mt-2 text-black"><%= student.name %></small>
                </div>
              <% end %>
            <% end %>
            <!-- More indicator -->
            <div class="text-center">
              <div class="avatar-circle bg-light text-muted d-flex align-items-center justify-content-center" 
                   style="width: 60px; height: 60px; border-radius: 50%; border: 2px dashed #dee2e6;">
                <span style="font-size: 0.8rem;">+<%= @user.institution.users.where(role: :student).count - 5 %></span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-3 text-md-end mt-3 mt-md-0">
          <p class="text-muted mb-1">
            <strong><%= @user.institution.total_students %></strong> total students
          </p>
          <small class="text-muted">Your rank: #<%= Institution.institution_rank_for_student(@user) %></small>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <!-- Quick Actions -->
  <div class="d-flex flex-column flex-md-row justify-content-between gap-2 gap-md-0 my-4">
    <%= link_to "Back to Dashboard", authenticated_root_path ,class:"btn btn-outline-primary" %>
  </div>
</div>

<style>

.hover-card {
  transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
}

.hover-card:hover {
  box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;
}

@media (max-width: 768px) {
  .d-flex.gap-3 {
    justify-content: center;
  }
  
  .d-flex.gap-2 {
    justify-content: center;
  }
}
</style>