config/routes.rb
Rails.application.routes.draw do
  get 'subscribers/create'
  
  get 'questions/show'
  get 'topics/index'
  get 'topics/show'
  get 'subjects/index'
  get 'subjects/show'
  
  resources :subjects do
    resources :topics, only: [:index, :new, :create]
  end
  
  resources :topics, except: [:index] do
    resources :sub_topics, only: [:index, :new, :create]
    resources :questions, only: [:new, :create]
  end
  
  resources :sub_topics, except: [:index, :new, :create]
  
  resources :questions, except: [:index, :new, :create]
  
  resources :badges
  
  resources :institutions do
    member do
      get :analytics_dashboard
      get :executive_summary
      get :engagement_analytics
      get :quiz_performance
      get :subject_breakdown
      get :student_distribution
      get :temporal_analysis
      get :comparative_analysis
      get :export_report
    end
  end
  
  resources :worlds do
    resources :levels do
      member do
        get :start_quiz
        get :level_preview
      end
    end
  end
  
  # Quiz routes
  get 'quiz/start', to: 'quiz#start', as: 'quiz_start'
  get 'quiz/question', to: 'quiz#question', as: 'quiz_question'
  get 'quiz/previous', to: 'quiz#previous_question', as: 'quiz_previous_question'
  post 'quiz/submit', to: 'quiz#submit', as: 'quiz_submit'
  get 'quiz/results', to: 'quiz#results', as: 'quiz_results'
  get 'quiz/history', to: 'quiz#history', as: 'quiz_history'
  get 'quiz/sessions', to: 'quiz#sessions', as: 'quiz_sessions'
  get 'quiz/quiz_select', to: 'quiz#quiz_select', as: 'quiz_select'
  get 'quiz/sessions/:id', to: 'quiz#show_session', as: 'quiz_session'
  get 'quiz/resume/:id', to: 'quiz#resume', as: 'resume_quiz'
  
  post 'quiz/sessions/:quiz_session_id/feedback', to: 'feedbacks#create', as: 'quiz_session_feedbacks'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  get 'users/user_new', to: 'users#user_new', as: 'user_new_user'
  post 'users/user_create', to: 'users#user_create', as: 'user_create_user'
  get 'users/:id/user_edit', to: 'users#user_edit', as: 'user_edit_user'
  patch 'users/:id/user_update', to: 'users#user_update', as: 'user_update_user'
  post 'reset_progress', to: 'users#reset_progress'
  get 'social', to: 'users#social', as: 'social'
  get '/profile/:nickname', to: 'users#profile', as: :profile
  get 'find_users', to: 'users#find_users', as: :find_users
  get 'mark_new_followers_seen', to: 'users#mark_new_followers_seen'
  
  resources :users do
    
    # Following routes
    post 'follows', to: 'user_follows#create'
    delete 'follows', to: 'user_follows#destroy'
     
    # Following-related pages
    get 'following', to: 'user_follows#following'
    get 'followers', to: 'user_follows#followers'
    get 'mutual', to: 'user_follows#mutual'
  end
  
  resources :study_groups do
    member do
      post :join
      get :leave
      get :invite_user
    end
    
    resources :study_group_memberships, only: [:destroy], path: 'members' do
      member do
        get :promote
        get :demote
      end
    end
    
    collection do
      get :leaderboards
    end
  end
  
  resources :study_group_invitations, only: [:index, :show] do
    member do
      get :accept
      get :decline
    end
  end
  
  authenticated :user, -> (user) { user.teacher? || user.admin? } do
    root to: "pages#teacher_dashboard", as: :teacher_root
  end
    
  authenticated :user, -> (user) { user.institution_admin? } do
    root to: "institutions#redirect_to_institution", as: :institution_root
  end
  
  authenticated :user, -> (user) { !user.teacher? && !user.admin? } do
    root to: "pages#home", as: :authenticated_root
  end
  
  # Unauthenticated user routes
  unauthenticated do
    root "pages#landing_page"
  end
  
  resources :subscribers, only: [:create]
  
  get 'pages/home', to: 'pages#home'
  get 'teacher_dashboard', to: 'pages#teacher_dashboard'
  get 'reports', to: 'pages#reports', as: 'reports'
  get 'configuration', to: 'pages#configuration', as: 'configuration'
  
  get 'pages/about'
  get 'pages/our_team'
  get 'pages/our_blog'
  get 'pages/csec_quizzes'
  get 'pages/contact_us'
  get 'pages/faqs'
  
  get 'leaderboard', to: 'leaderboard#index', as: 'leaderboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="border-top">
  <div class="container">
    <footer class="py-5">
      <div class="row">
        <div class="col-6 col-md-2 mb-3">
          <h5>Follow Us</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2">
  					  <%= link_to 'https://www.instagram.com/verdgemcsec/', class:"nav-link p-0 text-body-secondary" do %>
  						  <i class="bi bi-instagram"></i>
  						  <span class="">Instagram</span>
  					  <% end %>
  					</li>
  					
  					<li class="nav-item mb-2">
  					  <%= link_to "https://www.facebook.com/profile.php?id=61576219973814", class:"nav-link p-0 text-body-secondary" do %>
  						  <i class="bi bi-facebook"></i>
  						  <span class="">Facebook</span>
  					  <% end %>
  					</li>
					  
          </ul>
        </div>
  
        <div class="col-6 col-md-2 mb-3">
          <h5>About Us</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><%= link_to "About VerdGem", pages_about_path, class:"nav-link p-0 text-body-secondary"%></li>
            <li class="nav-item mb-2"><%= link_to "Our Blog", pages_our_blog_path, class:"nav-link p-0 text-body-secondary"%></li>
          </ul>
        </div>
  
        <div class="col-6 col-md-2 mb-3">
          <h5>Support</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><%= link_to "Contact Us", pages_contact_us_path, class:"nav-link p-0 text-body-secondary"%></li>
            <li class="nav-item mb-2"><%= link_to "FAQs", pages_faqs_path, class:"nav-link p-0 text-body-secondary"%></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Terms & Conditions</a></li>
          </ul>
        </div>
  
        <div class="col-md-5 offset-md-1 mb-3">
          <%= form_with model: Subscriber.new, class: "row g-3 align-items-center" do |f| %>
            <h5>Subscribe to our newsletter</h5>
            <p class="my-0">Monthly digest of what's new and exciting from us.</p>
            <div class="col-auto flex-grow-1">
              <%= f.email_field :email, class: "form-control", placeholder: "Your email address", required: true %>
            </div>
            <div class="col-auto">
              <%= f.submit "Subscribe", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
  
      <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
        <p>© 2025 VerdGem. All rights reserved.</p>
      </div>
    </footer>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg border-bottom">
  <div class="container-xl align-items-cente">
    <!-- Logo - Always visible -->
    <%= link_to root_path do %>
      <%= image_tag "Logo-full.png", alt: "VerdGem logo", class: "navbar-logo", width: 150 %>
    <% end %>
    
    <!-- User account section for mobile - Always visible if logged in -->
    <% if current_user %>
      <div class="d-lg-none ms-auto me-2">
        <div class="nav-item dropdown">
          <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
            <span class="avatar"><%= current_user.initials %></span>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
            <%= link_to 'My account', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </div>
      </div>
    <% end %>
    
    <!-- Mobile hamburger menu -->
    <button class="navbar-toggler mx-2 pt-2" type="button" data-bs-toggle="collapse" 
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon "><i class="bi bi-list"></i></span>
    </button>
 
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Main navigation items -->
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to authenticated_root_path, class:"nav-link d-flex align-items-center" do %>
            <i class="bi bi-house me-1"></i>
            <span>Home</span>
          <% end %>
        </li>
        
        <% if current_user && (current_user.admin? or current_user.teacher?) %>
          <li class="nav-item">
            <%= link_to subjects_path, class:"nav-link d-flex align-items-center" do %>
              <i class="bi bi-journal me-1"></i>
              <span>Subject</span>
            <% end %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to worlds_path, class:"nav-link d-flex align-items-center" do %>
            <i class="bi bi-backpack4 me-1"></i>
            <span>Adventure</span>
          <% end %>
        </li>
        
        <li class="nav-item">
          <%= link_to quiz_select_path, class:"nav-link d-flex align-items-center" do %>
            <i class="bi bi-check2-square me-1"></i>
            <span>Custom Quiz</span>
          <% end %>
        </li>
        
        <% if current_user && current_user.institution_admin? %>
          <li class="nav-item">
            <%= link_to institution_path(current_user.institution), class:"nav-link d-flex align-items-center" do %>
              <i class="bi bi-building me-1"></i>
              <span>Institution</span>
            <% end %>
          </li>
        <% end %>
        
        <% if current_user && current_user.student? %>
          <li class="nav-item">
            <%= link_to social_path, class:"nav-link d-flex align-items-center" do %>
              <i class="bi bi-people me-1"></i>
              <span>Social</span>
                <% if current_user.new_social_activity > 0 %>
                  <span class="badge bg-danger mx-1">
                    <%= current_user.new_social_activity %>
                  </span>
                <% end %>
              
            <% end %>
          </li>
        <% end %>
          
        <li class="nav-item">
          <%= link_to leaderboard_path, class:"nav-link d-flex align-items-center" do %>
            <i class="bi bi-trophy me-1"></i>
            <span>Leaderboard</span>
          <% end %>
        </li>
          
        <% if current_user && current_user.admin? %>
          <li class="nav-item">
            <%= link_to configuration_path, class:"nav-link d-flex align-items-center" do %>
              <i class="bi bi-gear me-1"></i>
              <span>Configuration</span>
            <% end %>
          </li>
        <% end %>
          
          <!-- Mobile-only divider for logged-in users -->
        <li class="nav-item d-lg-none border-top my-2"></li>
      </ul>
      
      <!-- Login/Signup or User Account (visible on desktop) -->
      <div class="d-none d-lg-flex navbar-nav">
        <% if current_user %>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link d-flex align-items-center text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
                
              <div class="d-none d-xl-block">
                <div class="d-flex align-items-center">
                  <span class="me-2"><%= !current_user.nickname.blank? ? current_user.nickname : current_user.first_name %></span>
                  <span class="badge bg-warning">Level <%= current_user.level %></span>
                </div>
                
                <!-- XP Progress Bar -->
                <div class="mt-1 progress" style="height: 6px; width: 120px;" title="<%= 1 %> / <%= 50 %> XP">
                  <div class="progress-bar bg-warning" role="progressbar" 
                       style="width: <%=  current_user.xp_percentage %>%;" 
                       aria-valuenow="<%= 45 %>" 
                       aria-valuemin="0" 
                       aria-valuemax="100">
                  </div>
                </div>
                <div class="mt-1 small text-muted d-flex justify-content-between">
                  <span><%= current_user.role.titleize %></span>
                  <% if current_user.student? %>
                    <span><%= current_user.xp_in_current_level %>/<%= current_user.xp_for_next_level - current_user.xp_for_current_level %> XP</span>
                  <% end %>
          
                </div>
              </div>
            </a>
            
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow py-0 px-2" style="width:300px;">
              <!-- Level summary in dropdown -->
              <div class="p-3 border-bottom">
                <div class=" mb-2">
                  <div>
                    <div class="fw-bold"><%= current_user.nickname %></div>
                    <div class="text-muted small">Level <%=  current_user.level %> <%= current_user.role.titleize %></div>
                  </div>
                </div>
                
                <hr style="border-color:grey !important; border-width:1px;"/>
              
              <!-- Regular menu options -->
              <div class="py-1">
                <%= link_to 'Upgrade', '#', class: 'dropdown-item px-0' %>
                <%= link_to 'My account', user_path(current_user), class: 'dropdown-item px-0' %>
                <%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item px-0', data: { turbo_method: :delete } %>
              </div>
            </div>
          </div>
        <% else %>
          <!-- Login/Signup buttons -->
          <div class="d-flex">
            <%= link_to new_user_session_path, class: "nav-link d-flex align-items-center" do %>
              <i class="bi bi-person me-1"></i>
              <span>Login</span>
            <% end %>
            <%= link_to new_user_registration_path, class: "nav-link d-flex align-items-center ms-2" do %>
              <span>Sign up</span>
            <% end %>
          </div>
        <% end %>
      </div>
      
      <!-- Mobile-only login/signup buttons (only shown when not logged in) -->
      <% if !current_user %>
        <div class="d-lg-none mt-2 pt-2">
          <div class="d-flex justify-content-around">
            <%= link_to new_user_session_path, class: "btn btn-outline-primary w-100 me-2" do %>
              <i class="bi bi-person me-1"></i>
              <span>Login</span>
            <% end %>
            <%= link_to new_user_registration_path, class: "btn btn-primary w-100" do %>
              <span>Sign up</span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>